### ISSUE TITLE
[Best Bundles] When putting a full bundle into new bundle, instead of refusing to do it, it just deletes the bundle

### ISSUE THREAD

**Issue by Thilpan** [DentedLeft/Dented-Modding#21] opened 2024-08-24 06:02 UTC
help

**Comment by DentedLeft** [comment] 2024-08-27 00:51
Thank you for raising this issue!  I will work on a fix for this.

**Comment by DentedLeft** [comment] 2024-08-30 23:46
@Thilpan Out of curiosity, are you using Best Bundles or Vanilla Sprinkles?

**Comment by DentedLeft** [comment] 2024-08-31 00:08
Fixed in version 1.0.2.

**Closed by DentedLeft** 2024-08-31 00:08 UTC
Labels: bug

**Comment by Thilpan** [comment] 2024-08-31 04:45
Sorry I did not see your second email, I’m using best bundles, btw is it
fixed now? Thanks

**Comment by DentedLeft** [comment] 2024-09-01 23:42
@Thilpan Yes, the issue is fixed as of version 1.0.2
